cck-fullstack/grace-shopper

- README.md
> added last name

- README.md
> will update

- package-lock.json
- package.json
- server/db/models/cartItem.js
- server/db/models/index.js
- server/db/models/item.js
- server/db/models/orderHistory.js
- server/db/models/shoppingCart.js
- server/db/models/user.js
> added all db models

- .travis.yml
- package.json
> travis test

- .travis.yml
- client/components/all-items.js
- client/components/cart.js
- client/store/cart.js
- package-lock.json
- package.json
- server/api/cartItems.js
- server/api/index.js
- server/api/orderHistories.js
- server/api/shoppingCarts.js
- server/db/models/index.js
- server/db/models/shoppingCart.js
- server/index.js
- server/routes/checkout.js
Checkout adds to OrderHistory and creates new ShoppingCart
- OrderHistory route exists and can be added to UserPage
Adding CartItems will create if it doesn't exist or update existing entry in db
-Information persists no matter who adds it but still not associated with a user
-Somehow broke redux item quantity display when adding (NEED TO FIX)
Added lodash for finding object in array
Some unused code still left in there from failed attempts
> More Sessions Cart

- .travis.yml
- client/components/all-items.js
- client/components/navbar.js
- package-lock.json
- package.json
- public/index.html
- script/seed.js
- server/db/models/item.js
> partial UI done

- client/components/createUser.js
- client/components/userForm.js
- client/store/user.js
- script/seed.js
- server/createUser/user.js
- server/db/models/admin.js
- server/db/models/user.js
> User page creation

- client/components/cart.js
- client/store/cart.js
- server/api/cartItems.js
cart buttons correctly interface with database
remove/add/delete counter also working
> all cart buttons working

- .travis.yml
- client/components/navbar.js
- package-lock.json
- package.json
> fix:travis

- client/routes.js
- server/db/models/user.spec.js
fixed issues with our route specs and basic notations
> bugfix: various bug fixes to routes and specs

- README.md
> CHORE: updated readme to include boilermaker information

- client/components/createUser.js
User will now be able to access homepage straight from login instead of staying on their own create page
> feat: user login now redirects to home page when user account is created

- client/app.js
- client/components/all-items.js
- client/components/carousel.js
- client/components/navbar.js
- package-lock.json
- package.json
- public/style.css
- script/seed.js
> style: built carousel feature and updated images

- client/components/auth-form.js
- client/components/userForm.js
> feat: front-end validations added to new account form and login form

- client/components/homePage.js
- client/components/navbar.js
- public/style.css
> style: applied basic styling to the home page

- client/components/admin-page.js
- client/store/items.js
- server/api/items.js
BUG redux not updating item view correctly
> feat(adminpage):delete item from db

- script/seed.js
- script/seedplus.js
> feat(seedfile): added seed file but pics don't work

- client/components/user-home.spec.js
- client/routes.js
> feat: login now redirects to front page if successful

- client/components/footer.js
- package-lock.json
- package.json
- public/index.html
- public/materialize-social.css
- server/auth/google.js
> style: footer and navbar update. pushing so stan and I have the same footer. 

- client/components/cart.js
- client/components/navbar.js
- client/components/stripe.js
> style: added mild styling to the cart and removed the header from the navbar

- client/components/footer.js
- public/index.html
> feat: social media links

- client/components/footer.js
- package-lock.json
> update: moved email button

- client/components/navbar.js
> fix: made button appear around dynamic username

- client/app.js
- client/components/footer.js
- client/components/navbar.js
- client/routes.js
- public/style.css
> update: sticky footer

- client/components/auth-form.js
- client/components/navbar.js
> update: create user was removed from nav and added to login

- server/index.js
> bug fix: attempt 3  to adjust oauth google sign in

- client/components/footer.js
- public/style.css
> update: footer has been gridified

- client/components/navbar.js
- public/style.css
> style: fixed navbar buttons and added logo image.

- client/components/all-items.js
- client/components/carousel.js
- client/components/cart.spec.js
- client/components/category.js
- client/components/dropdown.js
- client/components/single-item.js
- client/store/cart.js
- client/store/user.js
- server/api/cartItems.js
- server/api/cartItems.spec.js
- server/api/shoppingCarts.js
- server/auth/index.js
> test: Cartitems test specs

- client/components/all-items.js
> update: breadcrumb in all items

- client/components/navbar.js
> fixed navbar buttons, image, and signup buttons

- server/db/models/cartItem.js
> bugfix: cart no longer able to have negative values added to it

- client/components/all-items.js
- client/components/carousel.js
- client/components/category.js
- client/components/navbar.js
- client/components/pagination.js
- client/components/userPage.js
- public/style.css
> update: improved styling and pagination dummy component

- client/components/all-items.js
> bugfix: allitemfix, displays correctly now

- client/components/all-items.js
- client/components/cart.js
- client/components/category.js
- client/components/footer.js
- client/components/single-item.js
> feat: added local storage to the guest cart

- client/components/cart.js
- client/components/navbar.js
> bugfix: the bug has been fixed

- client/components/all-items.js
- client/components/cart.js
- client/components/category.js
- client/components/footer.js
- client/components/itemview.js
- client/components/navbar.js
- client/components/single-item.js
- public/style.css
- server/auth/index.js
> feat(footer): changed footer

- client/app.js
- client/components/footer.js
- client/components/navbar.js
- public/style.css
> bug(footer):missing div

- client/components/cart.js
- client/components/category.js
- client/components/footer.js
- client/components/single-item.js
> bug(newbranch):fixed loading bug

- client/components/carousel.js
- client/components/footer.js
> update: Footer ui

- client/components/all-items.js
- client/components/category.js
- client/components/footer.js
- client/components/navbar.js
- client/components/single-item.js
Toasts work now
Added loading circle
> feat(toast):fixed toasts on adding to cart

- client/components/all-items.js
- client/components/category.js
- client/components/footer.js
- client/components/navbar.js
- client/components/single-item.js
> bugfix: all buttons corrected and working, fixed UI

- client/components/cart.js
- client/routes.js
- public/style.css
> bugfix: viewall buttons fixed

- client/components/cart.js
- client/components/checkout.js
- client/components/stripe.js
- public/style.css
> UPDATE: added checkout features and cart total

- client/components/auth-form.js
- client/components/cart.js
- client/components/category.js
- client/components/checkout.js
- client/components/footer.js
- client/components/homePage.js
- client/components/navbar.js
- client/components/stripe.js
- client/store/items.js
- public/index.html
- public/style.css
- server/api/stripe.js
> feat(stripe):fixed broken stripe

- client/components/admin-page.js
- client/components/all-items.js
- client/components/cart.js
- client/components/dropdown.js
- client/components/stripe.js
> bugs:fixed minor visual bugs

- client/components/admin-page.js
- client/components/order-history.js
> update: order history and prices fixed

- client/components/admin-page.js
- client/routes.js
> update: fixed ui
